### ISSUE TITLE
Installation not working correctly

### ISSUE THREAD

**Issue by ewolff** [pivio/pivio-boot#4]
I did `curl https://raw.githubusercontent.com/pivio/pivio-boot/master/pivio.sh | /bin/sh` and opened http://localhost:8080/ . However, the links are to e.g. http://teramacbook:8080/app/query . `TeraMacBook` is the hostname of my local machine. But it is not resolvable - so the link is dead. I suggest to use `localhost` instead.

**Comment by oliverwehrens** [comment]
It takes the output of `hostname` to configure the url. Can you try to do a 

`` ping `hostname` `` 

and see if this works? I assume this is supposed to work on all machines. Let me know if I'm wrong.

**Comment by ewolff** [comment]
```
[wolff@TeraMacBook:~]ping `hostname`
PING teramacbook.local (10.100.10.172): 56 data bytes
64 bytes from 10.100.10.172: icmp_seq=0 ttl=64 time=0.078 ms
64 bytes from 10.100.10.172: icmp_seq=1 ttl=64 time=0.079 ms
^C
--- teramacbook.local ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.075/0.083/0.099/0.009 ms
[wolff@TeraMacBook:~]ping teramacbook
ping: cannot resolve teramacbook: Unknown host
```

So the problem is that Pivio uses `teramacbook` instead of `teramacbook.local`

**Comment by ewolff** [comment]
Actually the links work now. So the problems seems to be fixed.
