### ISSUE TITLE
Quickstart?

### ISSUE THREAD

**Issue by ewolff** [pivio/pivio-boot#5]
After the installation explained at http://pivio.io/docs/#section-quickstart I can go to the web site at http://localhost:8080/ (see screenshot) - but it is not clear what I can do now.

![noafd](https://user-images.githubusercontent.com/529318/29514289-4d8aa7a8-8668-11e7-9f3e-5e461d417c57.png)

**Comment by oliverwehrens** [comment]
I fixed the front page and pointed it to the demo script. If you execute it now you should have some demo data already imported. Hope this helps.

curl https://raw.githubusercontent.com/pivio/pivio-boot/master/demo.sh | /bin/sh

**Comment by ewolff** [comment]
Excellent - thanks!
